version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_MANAGEMENT_DEFAULT_USER=rabbitmq
      - RABBITMQ_MANAGEMENT_DEFAULT_PASS=123456
    restart: always
    ports:
      - 5672:5672
      - 15672:15672